version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - database

networks:
  database:
    driver: bridge
