version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - database

networks:
  database:
    driver: bridge
